#! /bin/sh
pkill sxhkd
sxhkd &
#pgrep -x sxhkd

#pkill picom
#picom -f --daemon --config $HOME/.config/picom/picom.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           13

bspc config top_padding          30
bspc config bottom_padding       30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore

#killall polybar
#polybar -c ~/.config/polybar/config.ini

